title: Creating mask for CT scan images using ITK snap
description: 'In this course we will learn how to use ITK snap to mask for CT scan images. '
template:
  repo: creating-mask-for-ct-scan-images-using-itk-snap-template
  name: creating-mask-for-ct-scan-images-using-itk-snap
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: Create mask using ITK snap. 
    description: this is a small course and it will take only 5-10 minutes to complete. 
    event: issues.assigned
    video: https://youtube.com/embed/c_hG1t9KVf4
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
